### ISSUE TITLE
Add help for the QA block

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/qa_block#12]
I suggest to add help texts for the QA block by supporting the `doc_items` mod.

Support is very simple, you don't need to depend. You just need to add
`_doc_items_longdesc = "<long description of what the QA block is good for goes here>"`
and
`_doc_items_usagehelp = "<explanation on how the QA block can be used goes here>"`

to the node def. of the QA block. There is no length limit.
The QA block is quite complex now, so I (and especially other users) would appreciate a good and understandable explanation. :-)

You can test the help entry by installing the Help modpack:
https://forum.minetest.net/viewtopic.php?f=9&t=15912

**Comment by bell07** [comment]
I know and like the doc_items mod. You get a great work for this! 
Unfortunately I am quite uninspired for <long description> or <explanation> so pull request with your descriptions welcome!

**Comment by Wuzzy2** [comment]
I'm not sure if I can trust myself in writing a complete help text for the block myself because I am not sure if I understood the mod 100%, to be honest. xD

**Comment by bell07** [comment]
Ok, I wrote some words: https://github.com/bell07/minetest-qa_block/commit/7cb996ac438fde67ad77fc46c7a635f776118e27
Please check if my english is enough. If something is not understandable you can ask in german

**Comment by Wuzzy2** [comment]
Thanks a bunch! You mod has been added to the list of mods supporting the Help modpack.

Here is the rewritten text for you:

```
local doc_items_longdesc =
[[The QA block is a quality assurance tool for mod and subgame developers.
By using the block it is possible to:
• Browse trough global Lua variables for deeper insight
• Execute ad-hoc Lua code for testing reasons in development
• Run predefined checks for quality assurance
]]

local doc_items_usagehelp =
[[Place the block and open the formspec using right mouse click.
Use the “Globals” tab for browsing trough global Lua variables.
Use the “Checks” tab to run Lua code. Editing the code before running is allowed.
The checks are read from the $MODPATH/checks directory.
It is possible to add new Lua files and run them without restarting the game. Just use the Refresh button.
Ususally the print() command is used in checks, so look in debug.txt or the Minetest console output.
Some chat commands are defined as shortcuts. See “/qa help” for more information.
Please note the “/qa ui” cannot store the current globals navigation, the navigation can be stored in the QA block only.
]]
```

Notes:
* Please remember to check your punctuation.
* It's “Lua”, not “lua”
* The Help modpack does line breaks automatically for you :-)


EDIT: Also please don't forget to keep the help up-to date as you add more features to the block.

**Comment by bell07** [comment]
Done. Thank you for the review. Updated..
Up-to-date docu grrr, developers nightmare ><
