### ISSUE TITLE
Colorize the list of variables

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/qa_block#14]
I suggest to use color coding for the list of variables in the Globals tab.

Use a different color for different variable types.
For example:

* Cyan for functions
* Purple for strings
* Yellow for numbers
* White for tables
* …

I don't care much about the actual colors, what is important they are easy on the eye and easy to distinguish.

**Comment by bell07** [comment]
Done in https://github.com/bell07/minetest-qa_block/commit/2842e4fce93a1fc252347769d58c31e90a582873

but I changed to purple for functions and cyan for strings because of darker purple color for meaningless functions...
