### ISSUE TITLE
Multi-line string in globals list breaks the display

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/qa_block#17]
If there is a string variable with line breaks, it is displayed incorrectly in the list; the list looks broken in this case because text gets written “over” other text.

This can be easily tested by adding any global multi-line string variable in any mod.

A possible solution would be just to eliminate all newlines before they get printed on the list and by replacing them with a literal “\n”.

**Comment by Wuzzy2** [comment]
Not fixed. Multiline strings are still broken in the globals list.

![](https://i.imgur.com/B7GS8aD.png)

Test string:
```
Hi
I
Am
A
String
```

**Comment by bell07** [comment]
The first attempt was mask the keys only. Now the values are proper masked and cutted too

**Comment by Wuzzy2** [comment]
OK. Looks fixed now. :+1:
