### ISSUE TITLE
Variable editing menu should only open for numbers and strings

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/qa_block#18]
In the Globals tab, you can double-click `boolean`s which opens the editing menu. But if you save, the variable becomes a string.
You can also overwrite an `userdata` variable like this and accidentally turn them into a string.

I think the editing menu should only open for strings and numbers, but not for any other data type because it is only able to save values of these types.

**Comment by bell07** [comment]
Fixed in https://github.com/bell07/minetest-qa_block/commit/26a68814c089259cf7113d170b981a0a860ad59b
Boolean are editable now. The type selection is a toggle button instead of checkbox.

**Comment by Wuzzy2** [comment]
:+1:
