### ISSUE TITLE
minetest.chat_send_all --> log

### ISSUE THREAD

**Issue by daretmavi** [minetest-mods/qa_block#21]
Hi,

can you change `print` function `minetest.chat_send_all(outsting)` to `minetest.log(outsting)`?

The reason is, that `.log` is logged into the `debug.txt` by default. It's easier to analyze it.

**Comment by bell07** [comment]
The idea for chat_send_all() was to see the output directly ingame, without switching to any console or file

**Comment by daretmavi** [comment]
Understand,
Anyway, in the current minetest version, I can not see much difference between chat and log messages.
Only log is logged into debug.txt and chat is not (by default).
So I would say, log is better for development - at least it is easier to get back to them. What do you think?

Btw. super tool 👍
